// enums.ts
export enum AssessmentType {
    TEST = 'TEST',
    FINAL_TEST_AT_EXAM_TIME = 'FINAL_TEST_AT_EXAM_TIME',
    WORK_DEVELOPMENT = 'WORK_DEVELOPMENT',
    WORK_DELIVERY = 'WORK_DELIVERY',
    GROUP_WORK_SUBMISSION = 'GROUP_WORK_SUBMISSION',
    WORK_PRESENTATION = 'WORK_PRESENTATION',
    GROUP_WORK_PRESENTATION = 'GROUP_WORK_PRESENTATION',
    MONOGRAPH = 'MONOGRAPH',
    INDIVIDUAL_PRACTICAL_EXERCISE = 'INDIVIDUAL_PRACTICAL_EXERCISE',
    PITCH = 'PITCH',
    FINAL_EXAM = 'FINAL_EXAM',
    ORAL_EXAM = 'ORAL_EXAM'
}
